### ISSUE TITLE
`blank?` is missing

### ISSUE THREAD

**Issue by stevesparks** [birarda/logan#18]
I have some code that creates a Logan client, and inserts some todos. If I do not need Rails, then when I go to create my todo, I get the following:

```
irb(main):003:0> target = @client.project_by_name("Test Project")
=> #<Logan::Project:0x007fa1c2b414d0 @id=6949038, @name="Test Project">
irb(main):004:0> team = {}
=> {}
irb(main):005:0>  @client.generate_todolist(target, team, iteration_id: 1)
Writing into project "Test Project"
Saving list "Iteration 1 Recurring Todos"
Creating unassigned todo: Communicate any training, vacations, or other time off to the client
NoMethodError: undefined method `blank?' for nil:NilClass
	from /Users/barbecuesteve/.gem/ruby/2.1.1/gems/logan-0.1.1/lib/logan/todo.rb:22:in `post_json'
	from /Users/barbecuesteve/.gem/ruby/2.1.1/gems/logan-0.1.1/lib/logan/todolist.rb:92:in `create_todo'
...
irb(main):006:0> 
```

I find that I can make this error go away by either requiring `rails`, or by simply adding that method from the [source](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/blank.rb):

```
class Object
  def blank?
    respond_to?(:empty?) ? !!empty? : !self
  end
end
```

Please address.

**Comment by bdunlap** [comment]
this is back in 0.2.2, see line 25 of logan/todo.rb

**Comment by bdunlap** [comment]
My mistake, I looked again and saw that you didn't remove the call to blank in 2ebd2fb but just removed it from the default code path. Somehow my code just triggered it at line 25 though.

**Comment by birarda** [comment]
@bdunlap thanks for highlighting that - was reintroduced with a PR from a contributor.

I'll re-open to fix this.

**Comment by bdunlap** [comment]
great thanks!

**Comment by RobertDeRose** [comment]
@birarda any word on a fix for this?
